# Generated by Django 5.1.5 on 2025-01-30 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('government', models.CharField(choices=[('c', 'cairo'), ('g', 'giza'), ('a', 'alexandria'), ('b', 'behira'), ('d', 'dakahlia'), ('k', 'qalyubia'), ('s', 'sohag'), ('q', 'qena'), ('f', 'fayoum'), ('m', 'menofia'), ('s', 'suez'), ('n', 'new valley'), ('w', 'wadi el gedid'), ('l', 'luxor'), ('t', 'tahta'), ('m', 'matruh'), ('b', 'bani suef'), ('p', 'port said'), ('s', 'sinai'), ('k', 'kafr el sheikh'), ('f', 'fayoum'), ('u', 'damietta'), ('r', 'red sea'), ('s', 'sharqia')], default='c', max_length=1)),
                ('details', models.TextField(blank=True, max_length=200)),
                ('price', models.FloatField(default=0)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='AvailableDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('sa', 'Saturday'), ('su', 'Sunday'), ('mo', 'Monday'), ('tu', 'Tuesday'), ('we', 'Wednesday'), ('th', 'Thursday'), ('fr', 'Friday')], max_length=2)),
                ('max_appointments', models.PositiveIntegerField(default=0)),
                ('current_appointments', models.PositiveIntegerField(default=0)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.location')),
            ],
        ),
    ]
