# Generated by Django 5.1.5 on 2025-01-30 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_availableday_time_from_availableday_time_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='bio',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='availableday',
            name='day_of_week',
            field=models.CharField(choices=[('SA', 'Saturday'), ('SU', 'Sunday'), ('MO', 'Monday'), ('TU', 'Tuesday'), ('WE', 'Wednesday'), ('TH', 'Thursday'), ('FR', 'Friday')], max_length=2),
        ),
        migrations.AlterField(
            model_name='location',
            name='government',
            field=models.CharField(choices=[('CA', 'Cairo'), ('GI', 'Giza'), ('AL', 'Alexandria'), ('BE', 'Beheira'), ('DA', 'Dakahlia'), ('QA', 'Qalyubia'), ('SO', 'Sohag'), ('QE', 'Qena'), ('FA', 'Fayoum'), ('MN', 'Menofia'), ('SU', 'Suez'), ('NV', 'New Valley'), ('WG', 'Wadi El Gedid'), ('LX', 'Luxor'), ('MT', 'Matruh'), ('BS', 'Bani Suef'), ('PS', 'Port Said'), ('SI', 'Sinai'), ('KS', 'Kafr El Sheikh'), ('DM', 'Damietta'), ('RS', 'Red Sea'), ('SH', 'Sharqia')], default='CA', max_length=2),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('day', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='medical.availableday')),
                ('doctor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='medical.doctor')),
                ('location', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='medical.location')),
                ('patient', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='medical.patient')),
            ],
        ),
    ]
