# Generated by Django 5.1.5 on 2025-02-13 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0003_doctor_bio_alter_availableday_day_of_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='price',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
