# Generated by Django 5.1.5 on 2025-02-13 15:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0004_alter_location_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availableday',
            name='max_appointments',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
