# Generated by Django 5.1.5 on 2025-02-13 15:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0005_alter_availableday_max_appointments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availableday',
            name='max_appointments',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
