# Generated by Django 5.1.5 on 2025-02-17 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0006_alter_availableday_max_appointments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
    ]
