# Generated by Django 5.1.5 on 2025-02-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0009_remove_appointment_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
