# Generated by Django 5.1.5 on 2025-02-17 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0011_rename_appointment_date_appointment_reverse_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='predict_time_end',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='predict_time_start',
        ),
    ]
