# Generated by Django 5.1.5 on 2025-02-06 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_reset_code_user_reset_code_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='reset_code',
            new_name='password_reset_code',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='reset_code_time',
            new_name='reset_code_created_at',
        ),
    ]
